### ISSUE TITLE
Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by dtagdev1** [fragaria/angular-daterangepicker#66] opened 2015-06-03 05:01 UTC
current, I am using v0.1.14. but, I still have problems on. help me !

TypeError: Cannot read property 'remove' of null
    at angular-daterangepicker.js:179
    at Scope.$broadcast (angular.js:14785)
    at Scope.$destroy (angular.js:14405)
    at cleanupLastView (angular-ui-router.js:3936)
    at angular-ui-router.js:3969
    at publicLinkFn (angular.js:6995)
    at updateView (angular-ui-router.js:3959)
    at angular-ui-router.js:3921
    at Scope.$broadcast (angular.js:14785)
    at $state.transition.resolved.then.$state.transition (angular-ui-router.js:3311)

**Comment by krtek** [comment] 2015-06-03 06:25
Helo, 

I believe this is duplicate of #58 which will be fixed in next release.

(See this [pull request](https://github.com/fragaria/angular-daterangepicker/pull/60) by @marcelinhov2)

**Closed by krtek** 2015-06-03 06:25 UTC

**Comment by elm-** [comment] 2015-06-03 10:56
@krtek yes, that would fix it.

**Comment by elm-** [comment] 2015-06-03 10:57
@krtek when do you plan to do the next release? just so I know when to upgrade or use a fork. thanks

**Comment by krtek** [comment] 2015-06-03 20:12
Let's say this weekend? There are some other pull requests that I want to review and put into release.
