### ISSUE TITLE
Date vs. Moment object in watch function

### ISSUE THREAD

**Issue by danielmcquillen** [fragaria/angular-daterangepicker#50] opened 2015-04-28 02:36 UTC
Thanks for the awesome library. However, I'm confused about the data returned in the $watch function as shown in the example.

Before when I used daterangepicker by itself in my pre-Angular days, the daterangepicker callback would provide me with Moment objects. 

However, when I've set things up per the example in this repo, the start and end dates in the callback return either the type of start date and end date object the picker was configured with or -- when the user selects new ranges -- Date objects (not Moment objects set to the correct UTC).

Is there a way to configure angular-daterangepicker so that it returns Moment objects set to the correct UTC?

**Comment by krtek** [comment] 2015-06-07 15:59
Duplicate of #49? Closing.

**Closed by krtek** 2015-06-07 15:59 UTC
